spring.application.name=rag-llm

spring.datasource.url=jdbc:postgresql://localhost:5432/rag_llm
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.show-sql=false
logging.level.org.springframework.web=INFO

gemini.api.key=
gemini.base.url=https://generativelanguage.googleapis.com