spring.application.name=rag-llm

spring.datasource.url=jdbc:postgresql://localhost:5432/rag_llm
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
gemini.api.key=AIzaSyBVyyvPmmxyUB8CVcNLkIfc2KGDCPDV__I
